services:
  demo:
    image: hydra035/hack #hack
    volumes:
      - /Users/bluh/Documents/GitHub/Binge/hackchallenge/add_dining_halls_and_menus.py:/app/add_dining_halls_and_menus.py
      - /Users/bluh/Documents/GitHub/Binge/hackchallenge/projectdb.py:/app/projectdb.py
      - /Users/bluh/Documents/GitHub/Binge/hackchallenge/eateries.json:/app/eateries.json

      # - /Users/bluh/Binge/hackchallenge:/app

      # - ./instance:/app/instance
    working_dir: /app
    ports:
      - "8000:8000"
    command: python3 /app/add_dining_halls_and_menus.py
    env_file: .env
